[package]
name = "elayr"
version = "0.1.0"
authors = [
        "Nicolas Argyriou <argyriou@etu.unistra.fr>",
        "Quentin Gliech <quentin.gliech@etu.unistra.fr>"
]


[dependencies]
utf8-ranges = "1.0.0"

[dependencies.nom]
version = "^3.2"
features = ["nightly"]
